export const movieTranslations = {
  en: {
    posterAlt: "{{title}} poster", noPoster: "No poster available for {{title}}", noRatings: "No external ratings are available for this title yet.", watched: "Watched", want: "Want to watch", unknownYear: "Year unknown",
    emptyTitle: "Nothing here yet", emptyDescription: "Discover a movie and add it to this collection.", errors: { save: "Could not save this movie.", load: "Could not load your movie library.", search: "Could not search for movies.", saved: "Could not load the saved movie.", details: "Could not load movie details.", recommendation: "Could not generate movie recommendations.", rewrite: "Could not rewrite the critique." },
    critics: "Critics & audiences", ratingsNote: "Scores are supplied by OMDb and remain the property of their respective sources. Availability varies by title.", story: "Story", director: "Director", genre: "Genre", released: "Released", country: "Country", language: "Language", boxOffice: "Box office", cast: "Cast", awards: "Awards",
    noteTitle: "Your movie note", noteHelp: "Keep it in your queue or record what you thought after watching.", yourScore: "Your score", watchedOn: "Watched on", critique: "Short critique", critiquePlaceholder: "What worked, what did not, and what stayed with you?", remove: "Remove", saving: "Saving…", saveChanges: "Save changes", markWatched: "Mark watched",
    enhanceWithAi: "Enhance with AI", rewriteTitle: "Review AI rewrite", rewriteDescription: "Compare the suggestion before changing your critique.", yourOriginal: "Your original", aiSuggestion: "Enhanced version", rewriting: "Improving your critique…", rewritePrivacy: "The proposal is temporary. Your critique changes only after you accept it, and it is saved only when you save the movie.", cancelRewrite: "Cancel", rephrase: "Rephrase", acceptRewrite: "Accept",
    pages: { want: { eyebrow: "Movie library", title: "Want to watch", description: "The films waiting for the right night." }, watched: { eyebrow: "Movie library", title: "Watched & rated", description: "Your viewing history, personal scores, and short critiques." }, suggestions: { eyebrow: "Personal recommendations", title: "AI movie suggestions", description: "Four verified movies shaped primarily by your recent taste, with all-time favourites as lighter anchors." }, discover: { eyebrow: "Movie library", title: "Discover movies", description: "Search the movie catalogue, compare ratings, and build your personal watch history." } },
    moviesCount: "{{count}} movies", tasteTitle: "Recommendations shaped by your taste", tasteDescription: "Recent ratings are the primary signal; up to five older all-time favourites provide lighter stability. We send only movie metadata, scores, and short critiques—never account identity—and verify every generated title through OMDb.", finding: "Finding matches…", anotherSet: "Try another set", suggest: "Suggest movies", ratedAvailable: "{{count}} recent ratings available · minimum 3",
    bestMatch: "Best AI match", verified: "Verified through OMDb", tonight: "Tonight's top suggestion", basedOn: "Based on your recent ratings", viewAdd: "View details & add", moreMatches: "More matches for you", alternatives: "Three alternatives from the same taste profile.", inspect: "Select a movie to inspect it", match: "#{{number}} match", view: "View", suggestionEmptyTitle: "Your next movie starts with your ratings", suggestionEmptyDescription: "Rate at least three watched movies. Better scores and critiques produce a more personal recommendation.",
    findTitle: "Find your next movie", findDescription: "Search by title. Open a result to see every rating source available before adding it.", queryPlaceholder: "Try The Matrix, Parasite, or Dune…", movieTitle: "Movie title", search: "Search", results: "Search results", searching: "Searching the catalogue…", matching: "{{count}} matching titles", featureSearch: "Search the catalogue", featureSearchHelp: "Find movies by title through OMDb.", featureQueue: "Build your queue", featureQueueHelp: "Save films for later without rating them yet.", featureReview: "Remember your take", featureReviewHelp: "Score watched films and write a concise critique.", noMatches: "No movies matched that title. Try a shorter or alternate title.",
    insights: { title: "Your movie highlights", longest: "Longest watch", highestRated: "Highest rated", oldestRelease: "Oldest release", newestRelease: "Newest release", recentlyWatched: "Recently watched", categories: "Browse by genre", all: "All", minutes: "{{count}} min", rating: "{{rating}} / 10", tied: "{{count}} movies tied", missingMetadata: "Add runtime, release year, rating, or watched-date metadata to unlock movie highlights." }
  },
  de: {
    posterAlt: "Poster zu {{title}}", noPoster: "Kein Poster für {{title}} verfügbar", noRatings: "Für diesen Titel sind noch keine externen Bewertungen verfügbar.", watched: "Gesehen", want: "Möchte ich sehen", unknownYear: "Jahr unbekannt",
    emptyTitle: "Noch nichts vorhanden", emptyDescription: "Entdecke einen Film und füge ihn dieser Sammlung hinzu.", errors: { save: "Der Film konnte nicht gespeichert werden.", load: "Deine Filmbibliothek konnte nicht geladen werden.", search: "Die Filmsuche ist fehlgeschlagen.", saved: "Der gespeicherte Film konnte nicht geladen werden.", details: "Die Filmdetails konnten nicht geladen werden.", recommendation: "Filmempfehlungen konnten nicht erstellt werden.", rewrite: "Die Kritik konnte nicht umformuliert werden." },
    critics: "Kritik & Publikum", ratingsNote: "Die Bewertungen stammen von OMDb und bleiben Eigentum der jeweiligen Quellen. Die Verfügbarkeit variiert je nach Titel.", story: "Handlung", director: "Regie", genre: "Genre", released: "Veröffentlicht", country: "Land", language: "Sprache", boxOffice: "Einspielergebnis", cast: "Besetzung", awards: "Auszeichnungen",
    noteTitle: "Deine Filmnotiz", noteHelp: "Behalte ihn auf deiner Liste oder notiere nach dem Ansehen deine Meinung.", yourScore: "Deine Bewertung", watchedOn: "Gesehen am", critique: "Kurze Kritik", critiquePlaceholder: "Was war gut, was nicht, und was ist dir geblieben?", remove: "Entfernen", saving: "Wird gespeichert…", saveChanges: "Änderungen speichern", markWatched: "Als gesehen markieren",
    enhanceWithAi: "Mit KI verbessern", rewriteTitle: "KI-Überarbeitung prüfen", rewriteDescription: "Vergleiche den Vorschlag, bevor deine Kritik geändert wird.", yourOriginal: "Dein Original", aiSuggestion: "Verbesserte Version", rewriting: "Deine Kritik wird verbessert…", rewritePrivacy: "Der Vorschlag ist vorläufig. Deine Kritik ändert sich erst nach der Annahme und wird erst beim Speichern des Films gespeichert.", cancelRewrite: "Abbrechen", rephrase: "Neu formulieren", acceptRewrite: "Übernehmen",
    pages: { want: { eyebrow: "Filmbibliothek", title: "Möchte ich sehen", description: "Filme, die auf den richtigen Abend warten." }, watched: { eyebrow: "Filmbibliothek", title: "Gesehen & bewertet", description: "Dein Verlauf, deine Bewertungen und kurzen Kritiken." }, suggestions: { eyebrow: "Persönliche Empfehlungen", title: "KI-Filmvorschläge", description: "Vier geprüfte Filme, hauptsächlich nach deinem aktuellen Geschmack und sanft verankert durch langjährige Favoriten." }, discover: { eyebrow: "Filmbibliothek", title: "Filme entdecken", description: "Durchsuche den Katalog, vergleiche Bewertungen und baue deine Filmhistorie auf." } },
    moviesCount: "{{count}} Filme", tasteTitle: "Empfehlungen nach deinem Geschmack", tasteDescription: "Aktuelle Bewertungen sind das Hauptsignal; bis zu fünf ältere Lieblingsfilme sorgen mit geringerem Gewicht für Stabilität. Wir senden nur Filmdaten, Bewertungen und kurze Kritiken—nie deine Kontoidentität—und prüfen jeden Titel über OMDb.", finding: "Treffer werden gesucht…", anotherSet: "Andere Vorschläge", suggest: "Filme vorschlagen", ratedAvailable: "{{count}} aktuelle Bewertungen verfügbar · mindestens 3",
    bestMatch: "Beste KI-Übereinstimmung", verified: "Über OMDb geprüft", tonight: "Top-Vorschlag für heute", basedOn: "Basierend auf deinen letzten Bewertungen", viewAdd: "Details ansehen & hinzufügen", moreMatches: "Weitere Treffer für dich", alternatives: "Drei Alternativen aus demselben Geschmacksprofil.", inspect: "Film auswählen, um Details zu sehen", match: "Treffer Nr. {{number}}", view: "Ansehen", suggestionEmptyTitle: "Dein nächster Film beginnt mit deinen Bewertungen", suggestionEmptyDescription: "Bewerte mindestens drei gesehene Filme. Bewertungen und Kritiken machen die Empfehlung persönlicher.",
    findTitle: "Finde deinen nächsten Film", findDescription: "Suche nach Titel. Öffne einen Treffer, um vor dem Hinzufügen alle verfügbaren Bewertungen zu sehen.", queryPlaceholder: "Zum Beispiel Matrix, Parasite oder Dune…", movieTitle: "Filmtitel", search: "Suchen", results: "Suchergebnisse", searching: "Katalog wird durchsucht…", matching: "{{count}} passende Titel", featureSearch: "Katalog durchsuchen", featureSearchHelp: "Finde Filme über OMDb nach Titel.", featureQueue: "Merkliste aufbauen", featureQueueHelp: "Speichere Filme für später, ohne sie schon zu bewerten.", featureReview: "Deine Meinung festhalten", featureReviewHelp: "Bewerte gesehene Filme und schreibe eine kurze Kritik.", noMatches: "Kein Film passt zu diesem Titel. Versuche einen kürzeren oder alternativen Titel.",
    insights: { title: "Deine Film-Highlights", longest: "Längster Film", highestRated: "Höchste Bewertung", oldestRelease: "Älteste Veröffentlichung", newestRelease: "Neueste Veröffentlichung", recentlyWatched: "Zuletzt gesehen", categories: "Nach Genre filtern", all: "Alle", minutes: "{{count}} Min.", rating: "{{rating}} / 10", tied: "{{count}} Filme gleichauf", missingMetadata: "Ergänze Laufzeit, Erscheinungsjahr, Bewertung oder Sichtungsdatum, um Film-Highlights freizuschalten." }
  },
  hu: {
    posterAlt: "{{title}} plakátja", noPoster: "Nincs elérhető plakát ehhez: {{title}}", noRatings: "Ehhez a filmhez még nincs külső értékelés.", watched: "Megnézve", want: "Megnézendő", unknownYear: "Ismeretlen év",
    emptyTitle: "Még nincs itt semmi", emptyDescription: "Fedezz fel egy filmet, és add hozzá ehhez a gyűjteményhez.", errors: { save: "A filmet nem sikerült menteni.", load: "A filmtárat nem sikerült betölteni.", search: "A filmkeresés sikertelen.", saved: "A mentett filmet nem sikerült betölteni.", details: "A film részleteit nem sikerült betölteni.", recommendation: "Nem sikerült filmajánlásokat készíteni.", rewrite: "Nem sikerült átírni a kritikát." },
    critics: "Kritikusok és közönség", ratingsNote: "A pontszámokat az OMDb biztosítja, és azok a megfelelő források tulajdonában maradnak. Az elérhetőség filmenként változik.", story: "Történet", director: "Rendező", genre: "Műfaj", released: "Megjelenés", country: "Ország", language: "Nyelv", boxOffice: "Jegybevétel", cast: "Szereplők", awards: "Díjak",
    noteTitle: "Saját filmjegyzet", noteHelp: "Tartsd a listádon, vagy írd le a véleményedet a megtekintés után.", yourScore: "Saját pontszám", watchedOn: "Megnézés dátuma", critique: "Rövid kritika", critiquePlaceholder: "Mi működött, mi nem, és mi maradt meg benned?", remove: "Eltávolítás", saving: "Mentés…", saveChanges: "Módosítások mentése", markWatched: "Megnézettnek jelölés",
    enhanceWithAi: "Javítás MI-vel", rewriteTitle: "MI-átírás ellenőrzése", rewriteDescription: "Hasonlítsd össze a javaslatot, mielőtt megváltoztatnád a kritikádat.", yourOriginal: "Eredeti szöveged", aiSuggestion: "Javított változat", rewriting: "A kritika javítása…", rewritePrivacy: "A javaslat ideiglenes. A kritikád csak elfogadás után változik meg, és csak a film mentésekor kerül mentésre.", cancelRewrite: "Mégse", rephrase: "Újrafogalmazás", acceptRewrite: "Elfogadás",
    pages: { want: { eyebrow: "Filmtár", title: "Megnézendő", description: "Filmek, amelyek a megfelelő estére várnak." }, watched: { eyebrow: "Filmtár", title: "Megnézve és értékelve", description: "Megtekintési előzményeid, pontszámaid és rövid kritikáid." }, suggestions: { eyebrow: "Személyes ajánlások", title: "MI-filmajánlások", description: "Négy ellenőrzött film, elsősorban a friss ízlésed, kisebb súllyal pedig régi kedvenceid alapján." }, discover: { eyebrow: "Filmtár", title: "Filmek felfedezése", description: "Keress a katalógusban, hasonlítsd össze az értékeléseket és építsd fel a filmtörténetedet." } },
    moviesCount: "{{count}} film", tasteTitle: "Az ízlésedhez igazított ajánlások", tasteDescription: "A friss értékelések az elsődleges jelek; legfeljebb öt régebbi kedvenc kisebb súllyal stabilizálja a profilt. Csak filmadatokat, pontszámokat és rövid kritikákat küldünk—fiókazonosságot soha—és minden címet ellenőrzünk az OMDb-n.", finding: "Találatok keresése…", anotherSet: "Másik csomag", suggest: "Filmek ajánlása", ratedAvailable: "{{count}} friss értékelés elérhető · minimum 3",
    bestMatch: "Legjobb MI-találat", verified: "OMDb-n ellenőrizve", tonight: "Mai legjobb ajánlat", basedOn: "A legutóbbi értékeléseid alapján", viewAdd: "Részletek és hozzáadás", moreMatches: "További találatok", alternatives: "Három alternatíva ugyanebből az ízlésprofilból.", inspect: "Válassz filmet a részletekhez", match: "{{number}}. találat", view: "Megnézem", suggestionEmptyTitle: "A következő filmed az értékeléseiddel kezdődik", suggestionEmptyDescription: "Értékelj legalább három megnézett filmet. A pontszámok és kritikák személyesebbé teszik az ajánlást.",
    findTitle: "Találd meg a következő filmedet", findDescription: "Keress cím alapján. Nyiss meg egy találatot, hogy hozzáadás előtt lásd az összes elérhető értékelést.", queryPlaceholder: "Próbáld: Matrix, Parasite vagy Dune…", movieTitle: "Film címe", search: "Keresés", results: "Keresési találatok", searching: "Keresés a katalógusban…", matching: "{{count}} egyező cím", featureSearch: "Keresés a katalógusban", featureSearchHelp: "Keress filmeket cím szerint az OMDb-n.", featureQueue: "Építsd fel a listád", featureQueueHelp: "Ments filmeket későbbre értékelés nélkül.", featureReview: "Őrizd meg a véleményed", featureReviewHelp: "Pontozd a megnézett filmeket és írj rövid kritikát.", noMatches: "Nincs egyező film. Próbálj rövidebb vagy másik címet.",
    insights: { title: "Filmes csúcspontjaid", longest: "Leghosszabb film", highestRated: "Legmagasabb értékelés", oldestRelease: "Legrégebbi megjelenés", newestRelease: "Legújabb megjelenés", recentlyWatched: "Legutóbb megnézve", categories: "Szűrés műfaj szerint", all: "Összes", minutes: "{{count}} perc", rating: "{{rating}} / 10", tied: "{{count}} film holtversenyben", missingMetadata: "Adj meg játékidőt, megjelenési évet, értékelést vagy megtekintési dátumot a filmes csúcspontokhoz." }
  },
} as const
