export const netWorthTranslations = {
  en: {
    eyebrow: "Financial position", title: "Net worth", description: "Track what you own and owe separately from everyday spending.",
    addItem: "Add item", editItem: "Edit item", close: "Close", save: "Save item", saving: "Saving…", snapshot: "Save today's snapshot", snapshotting: "Saving snapshot…", snapshotSaved: "Today's net-worth snapshot was saved.",
    assets: "Assets", liabilities: "Liabilities", netWorth: "Net worth", trackedItems: "{{count}} active items", currency: "Currency", history: "Net-worth history", historyHelp: "Snapshots show how assets, debt, and net worth change over time.", noHistory: "Add an item or save a snapshot to begin your history.",
    holdings: "Assets and liabilities", holdingsHelp: "Bank-linked values follow the latest synchronized balance. Manual values change when you edit them.", emptyTitle: "No net-worth items yet", emptyHelp: "Add cash, property, investments, loans, or connect an existing bank balance.",
    name: "Name", namePlaceholder: "e.g. Savings account or car loan", kind: "Type", asset: "Asset", liability: "Liability", category: "Category", value: "Current value", ownership: "Your ownership", dataSource: "Value source", manual: "Manual value", linkedBank: "Linked bank account", bankBalanceHelp: "The synchronized bank balance replaces the manual value.", notes: "Notes", notesPlaceholder: "Optional valuation details", active: "Include in totals", cancel: "Cancel", edit: "Edit", delete: "Delete", deleteTitle: "Delete this net-worth item?", deleteHelp: "Its valuation history will also be deleted. Expenses and bank data are not affected.", deleteConfirm: "Delete item", linked: "Linked", owned: "{{percent}}% owned", updated: "Balance updated {{date}}",
    categories: { CASH: "Cash", BANK: "Bank account", INVESTMENT: "Investment", PROPERTY: "Property", VEHICLE: "Vehicle", BUSINESS: "Business", LOAN: "Loan", CREDIT_CARD: "Credit card", OTHER: "Other" },
    loadError: "Could not load net-worth data.", saveError: "Could not save this item.", deleteError: "Could not delete this item.", snapshotError: "Could not save today's snapshot.",
  },
  de: {
    eyebrow: "Finanzlage", title: "Nettovermögen", description: "Erfasse Besitz und Schulden getrennt von den täglichen Ausgaben.",
    addItem: "Posten hinzufügen", editItem: "Posten bearbeiten", close: "Schließen", save: "Posten speichern", saving: "Speichern…", snapshot: "Heutigen Stand speichern", snapshotting: "Stand wird gespeichert…", snapshotSaved: "Der heutige Vermögensstand wurde gespeichert.",
    assets: "Vermögenswerte", liabilities: "Verbindlichkeiten", netWorth: "Nettovermögen", trackedItems: "{{count}} aktive Posten", currency: "Währung", history: "Vermögensverlauf", historyHelp: "Snapshots zeigen die Entwicklung von Vermögen, Schulden und Nettovermögen.", noHistory: "Füge einen Posten hinzu oder speichere einen Stand, um den Verlauf zu beginnen.",
    holdings: "Vermögen und Schulden", holdingsHelp: "Verknüpfte Bankwerte folgen dem letzten synchronisierten Saldo. Manuelle Werte ändern sich beim Bearbeiten.", emptyTitle: "Noch keine Vermögensposten", emptyHelp: "Füge Bargeld, Immobilien, Anlagen oder Kredite hinzu oder verknüpfe einen Banksaldo.",
    name: "Name", namePlaceholder: "z. B. Sparkonto oder Autokredit", kind: "Typ", asset: "Vermögenswert", liability: "Verbindlichkeit", category: "Kategorie", value: "Aktueller Wert", ownership: "Dein Anteil", dataSource: "Wertquelle", manual: "Manueller Wert", linkedBank: "Verknüpftes Bankkonto", bankBalanceHelp: "Der synchronisierte Banksaldo ersetzt den manuellen Wert.", notes: "Notizen", notesPlaceholder: "Optionale Bewertungsdetails", active: "In Summen einbeziehen", cancel: "Abbrechen", edit: "Bearbeiten", delete: "Löschen", deleteTitle: "Diesen Vermögensposten löschen?", deleteHelp: "Auch sein Bewertungsverlauf wird gelöscht. Ausgaben und Bankdaten bleiben unberührt.", deleteConfirm: "Posten löschen", linked: "Verknüpft", owned: "{{percent}}% Anteil", updated: "Saldo aktualisiert: {{date}}",
    categories: { CASH: "Bargeld", BANK: "Bankkonto", INVESTMENT: "Anlage", PROPERTY: "Immobilie", VEHICLE: "Fahrzeug", BUSINESS: "Unternehmen", LOAN: "Kredit", CREDIT_CARD: "Kreditkarte", OTHER: "Sonstiges" },
    loadError: "Vermögensdaten konnten nicht geladen werden.", saveError: "Dieser Posten konnte nicht gespeichert werden.", deleteError: "Dieser Posten konnte nicht gelöscht werden.", snapshotError: "Der heutige Stand konnte nicht gespeichert werden.",
  },
  hu: {
    eyebrow: "Pénzügyi helyzet", title: "Nettó vagyon", description: "Kövesd külön a tulajdonodat és a tartozásaidat a napi kiadásoktól.",
    addItem: "Tétel hozzáadása", editItem: "Tétel szerkesztése", close: "Bezárás", save: "Tétel mentése", saving: "Mentés…", snapshot: "Mai állapot mentése", snapshotting: "Állapot mentése…", snapshotSaved: "A mai nettóvagyon-állapot elmentve.",
    assets: "Eszközök", liabilities: "Kötelezettségek", netWorth: "Nettó vagyon", trackedItems: "{{count}} aktív tétel", currency: "Pénznem", history: "Nettó vagyon alakulása", historyHelp: "A pillanatképek megmutatják az eszközök, adósságok és a nettó vagyon változását.", noHistory: "Adj hozzá egy tételt vagy ments pillanatképet az előzményekhez.",
    holdings: "Eszközök és tartozások", holdingsHelp: "A kapcsolt banki érték a legutóbbi szinkronizált egyenleget követi. A kézi érték szerkesztéskor változik.", emptyTitle: "Még nincs nettóvagyon-tétel", emptyHelp: "Adj hozzá készpénzt, ingatlant, befektetést vagy hitelt, illetve kapcsolj egy banki egyenleget.",
    name: "Név", namePlaceholder: "pl. megtakarítás vagy autóhitel", kind: "Típus", asset: "Eszköz", liability: "Kötelezettség", category: "Kategória", value: "Jelenlegi érték", ownership: "Tulajdoni hányadod", dataSource: "Érték forrása", manual: "Kézi érték", linkedBank: "Kapcsolt bankszámla", bankBalanceHelp: "A szinkronizált banki egyenleg felülírja a kézi értéket.", notes: "Megjegyzés", notesPlaceholder: "Opcionális értékelési részletek", active: "Számítson bele az összesítésbe", cancel: "Mégse", edit: "Szerkesztés", delete: "Törlés", deleteTitle: "Törlöd ezt a nettóvagyon-tételt?", deleteHelp: "Az értékelési előzménye is törlődik. A kiadásokat és banki adatokat ez nem érinti.", deleteConfirm: "Tétel törlése", linked: "Kapcsolt", owned: "{{percent}}% tulajdon", updated: "Egyenleg frissítve: {{date}}",
    categories: { CASH: "Készpénz", BANK: "Bankszámla", INVESTMENT: "Befektetés", PROPERTY: "Ingatlan", VEHICLE: "Jármű", BUSINESS: "Vállalkozás", LOAN: "Hitel", CREDIT_CARD: "Hitelkártya", OTHER: "Egyéb" },
    loadError: "A nettóvagyon-adatokat nem sikerült betölteni.", saveError: "A tételt nem sikerült menteni.", deleteError: "A tételt nem sikerült törölni.", snapshotError: "A mai állapotot nem sikerült menteni.",
  },
} as const
